src/main/java/com/sparta/nanglangeats/global/common/dto/CommonResponse.java, src/main/java/com/sparta/nanglangeats/global/common/entity/Timestamped.java, src/main/java/com/sparta/nanglangeats/global/common/exception/CustomException.java, src/main/java/com/sparta/nanglangeats/global/config/AuditingConfig.java, src/main/resources/application-datasource.yml, src/main/resources/application-jwt.yml, src/main/resources/application.properties, src/main/resources/application.yml
#1, #2, #6, #7, #8
- application datasource 정보 추가
- application 설정 파일 분리
- Timestamped 삭제 정보 추가
=> [feat] 프로젝트 설정 추가

src/main/java/com/sparta/nanglangeats/domain/user/entity/User.java, src/main/java/com/sparta/nanglangeats/domain/user/enums/UserRole.java, src/main/java/com/sparta/nanglangeats/global/common/dto/CommonResponse.java, src/main/java/com/sparta/nanglangeats/global/common/entity/Timestamped.java, src/main/java/com/sparta/nanglangeats/global/common/exception/CustomException.java, src/main/java/com/sparta/nanglangeats/global/config/AuditingConfig.java, src/main/resources/application-datasource.yml, src/main/resources/application-jwt.yml, src/main/resources/application.properties, src/main/resources/application.yml
=> [feat] 유저 엔티티 정의

src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/request/UserSignupRequest.java, src/main/java/com/sparta/nanglangeats/domain/user/repository/UserRepository.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/main/java/com/sparta/nanglangeats/global/common/exception/CustomFieldError.java, src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java, src/main/java/com/sparta/nanglangeats/global/common/exception/GlobalExceptionHandler.java, src/main/java/com/sparta/nanglangeats/global/common/exception/ParameterException.java, src/main/java/com/sparta/nanglangeats/global/config/AuthConfig.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/test/java/com/sparta/nanglangeats/domain/user/repository/UserRepositoryTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
=> [feat] Spring Security 설정

src/main/java/com/sparta/nanglangeats/domain/user/repository/UserRepository.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/main/java/com/sparta/nanglangeats/global/config/security/entrypoint/CustomAuthenticationEntryPoint.java, src/main/java/com/sparta/nanglangeats/global/config/security/filter/CustomAuthenticationFilter.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAccessDeniedHandler.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationFailureHandler.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java, src/main/java/com/sparta/nanglangeats/global/config/security/provider/CustomAuthenticationProvider.java, src/test/java/com/sparta/nanglangeats/domain/user/repository/UserRepositoryTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
> #21, #13, #17, #20
- 커스텀 인증 필터 구현
- 커스텀 인증 프로바이더 구현
- 커스텀 인증 성공 · 실패 핸들러 구현
- 인증 · 인가 예외 핸들러 구현
=> [feat] 커스텀 인증 구현

build.gradle, src/main/java/com/sparta/nanglangeats/domain/user/repository/UserRepository.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java, src/main/java/com/sparta/nanglangeats/global/config/AuditingConfig.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/main/java/com/sparta/nanglangeats/global/config/security/entrypoint/CustomAuthenticationEntryPoint.java, src/main/java/com/sparta/nanglangeats/global/config/security/filter/CustomAuthenticationFilter.java, src/main/java/com/sparta/nanglangeats/global/config/security/filter/JwtAuthenticationFilter.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAccessDeniedHandler.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationFailureHandler.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java, src/main/java/com/sparta/nanglangeats/global/config/security/jwt/JwtTokenProvider.java, src/main/java/com/sparta/nanglangeats/global/config/security/provider/CustomAuthenticationProvider.java, src/test/java/com/sparta/nanglangeats/domain/user/repository/UserRepositoryTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
> #15
- JWT 프로바이더 구현
- JWT 인증 필터 구현
- 로그인 성공 시 헤더에 JWT 추가
=> [feat] 커스텀 JWT 인증 구현

src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
=> [feat] Role Hierarchy 설정

README.md
> -
> README 파일 내용을 "to be updated"로 수정
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> [etc] README 수정

src/main/java/com/sparta/nanglangeats/global/common/util/ControllerUtil.java
> #35
- HttpStatus를 인자로 받아서 동적으로 사용할 수 있도록 코드 수정
=> [fix] ControllerUtil 매개변수 수정

src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/request/UserSignupRequest.java, src/main/java/com/sparta/nanglangeats/domain/user/entity/User.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/main/java/com/sparta/nanglangeats/domain/user/service/dto/request/UserSignupServiceRequest.java, src/main/java/com/sparta/nanglangeats/global/common/annotation/Email.java, src/main/java/com/sparta/nanglangeats/global/common/annotation/Password.java, src/main/java/com/sparta/nanglangeats/global/common/annotation/Username.java, src/main/java/com/sparta/nanglangeats/global/common/annotation/validator/EmailValidator.java, src/main/java/com/sparta/nanglangeats/global/common/annotation/validator/PasswordValidator.java, src/main/java/com/sparta/nanglangeats/global/common/annotation/validator/UsernameValidator.java, src/main/java/com/sparta/nanglangeats/global/common/entity/Timestamped.java, src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java, src/main/java/com/sparta/nanglangeats/global/common/exception/GlobalExceptionHandler.java, src/main/java/com/sparta/nanglangeats/global/common/util/ControllerUtil.java, src/main/java/com/sparta/nanglangeats/global/config/AuditingConfig.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java, src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java, src/test/java/com/sparta/nanglangeats/domain/user/controller/dto/request/UserSignupRequestTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
> #37
> 유저 회원 가입을 위한 검증 추가 및 회원 가입 로직 수정
=> [fix] 유저 회원 가입 기능 수정

src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
> #41
- 유저 생성 메서드명 create -> createUser로 더 명확하게 수정
=> [fix] 유저 회원 가입 메서드명 수정

src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
> #44
- Spring Security MethodSecurity 설정 추가
=> [feat] Spring Security MethodSecurity 설정 추가

src/main/java/com/sparta/nanglangeats/global/common/annotation/validator/UsernameValidator.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
=> [fix] UsernameValidator 수정

src/main/java/com/sparta/nanglangeats/global/common/annotation/validator/UsernameValidator.java, src/main/java/com/sparta/nanglangeats/global/common/exception/GlobalExceptionHandler.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
> #46
- HttpMessageNotReadableException 핸들러 추가
=> [feat] GlobalExceptionHandler 예외 핸들러 추가

src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/request/UserUpdateRequest.java, src/main/java/com/sparta/nanglangeats/domain/user/entity/User.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
=> [feat] 유저 정보 수정 기능 구현

src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java, src/main/java/com/sparta/nanglangeats/domain/user/entity/User.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java
=> [feat] 유저 회원 탈퇴 기능 구현

src/main/java/com/sparta/nanglangeats/domain/image/entity/Image.java, src/main/java/com/sparta/nanglangeats/domain/image/service/ImageService.java, src/main/java/com/sparta/nanglangeats/domain/product/controller/ProductController.java, src/main/java/com/sparta/nanglangeats/domain/product/entity/Product.java, src/main/java/com/sparta/nanglangeats/domain/product/service/ProductService.java, src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java
=> [feat] 상품 삭제 기능 구현

src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
=> [fix] - 유저 엔드포인트 URL 수정

src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/MyInfoResponse.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/UserDetailResponse.java, src/main/java/com/sparta/nanglangeats/domain/user/repository/UserRepository.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java, src/test/java/com/sparta/nanglangeats/domain/user/repository/UserRepositoryTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
> #62
- 마이페이지 조회
- 닉네임을 통한 유저 상세 정보 조회
=> [feat] 유저 정보 조회 기능 구현

src/main/java/com/sparta/nanglangeats/domain/auth/controller/AuthController.java, src/main/java/com/sparta/nanglangeats/domain/refresh_token/entity/RefreshToken.java, src/main/java/com/sparta/nanglangeats/domain/refresh_token/repository/RefreshTokenRepository.java, src/main/java/com/sparta/nanglangeats/domain/refresh_token/service/RefreshTokenService.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/MyInfoResponse.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/UserDetailResponse.java, src/main/java/com/sparta/nanglangeats/domain/user/repository/UserRepository.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java, src/main/java/com/sparta/nanglangeats/global/common/util/ControllerUtil.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/main/java/com/sparta/nanglangeats/global/config/security/filter/GlobalExceptionFilter.java, src/main/java/com/sparta/nanglangeats/global/config/security/filter/JwtAuthenticationFilter.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java, src/main/java/com/sparta/nanglangeats/global/config/security/jwt/JwtTokenProvider.java, src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java, src/test/java/com/sparta/nanglangeats/domain/user/repository/UserRepositoryTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
> #82
- 토큰 재발급 기능 구현
- 추후 Redis TTL 기능을 활용한 Refresh Token 관리 예정
=> [feat] 토큰 재발급 기능 구현

src/main/java/com/sparta/nanglangeats/domain/auth/controller/AuthController.java, src/main/java/com/sparta/nanglangeats/domain/refresh_token/entity/RefreshToken.java, src/main/java/com/sparta/nanglangeats/domain/refresh_token/repository/RefreshTokenRepository.java, src/main/java/com/sparta/nanglangeats/domain/refresh_token/service/RefreshTokenService.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/MyInfoResponse.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/UserDetailResponse.java, src/main/java/com/sparta/nanglangeats/domain/user/repository/UserRepository.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java, src/main/java/com/sparta/nanglangeats/global/common/util/ControllerUtil.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/main/java/com/sparta/nanglangeats/global/config/security/filter/GlobalExceptionFilter.java, src/main/java/com/sparta/nanglangeats/global/config/security/filter/JwtAuthenticationFilter.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java, src/main/java/com/sparta/nanglangeats/global/config/security/jwt/JwtTokenProvider.java, src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java, src/test/java/com/sparta/nanglangeats/domain/user/repository/UserRepositoryTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
=> [feat] 로그아웃 기능 구현

src/main/java/com/sparta/nanglangeats/domain/auth/controller/AuthController.java, src/main/java/com/sparta/nanglangeats/domain/delivery_address/controller/DeliveryAddressController.java, src/main/java/com/sparta/nanglangeats/domain/delivery_address/controller/dto/request/DeliveryAddressCreateRequest.java, src/main/java/com/sparta/nanglangeats/domain/delivery_address/entity/DeliveryAddress.java, src/main/java/com/sparta/nanglangeats/domain/delivery_address/repository/DeliveryAddressRepository.java, src/main/java/com/sparta/nanglangeats/domain/delivery_address/service/DeliveryAddressService.java, src/main/java/com/sparta/nanglangeats/domain/refresh_token/entity/RefreshToken.java, src/main/java/com/sparta/nanglangeats/domain/refresh_token/repository/RefreshTokenRepository.java, src/main/java/com/sparta/nanglangeats/domain/refresh_token/service/RefreshTokenService.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/UserController.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/MyInfoResponse.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/response/UserDetailResponse.java, src/main/java/com/sparta/nanglangeats/domain/user/entity/DeliveryAddress.java, src/main/java/com/sparta/nanglangeats/domain/user/entity/User.java, src/main/java/com/sparta/nanglangeats/domain/user/repository/UserRepository.java, src/main/java/com/sparta/nanglangeats/domain/user/service/UserService.java, src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java, src/main/java/com/sparta/nanglangeats/global/common/util/ControllerUtil.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/main/java/com/sparta/nanglangeats/global/config/security/filter/GlobalExceptionFilter.java, src/main/java/com/sparta/nanglangeats/global/config/security/filter/JwtAuthenticationFilter.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java, src/main/java/com/sparta/nanglangeats/global/config/security/jwt/JwtTokenProvider.java, src/test/java/com/sparta/nanglangeats/domain/user/controller/UserControllerTest.java, src/test/java/com/sparta/nanglangeats/domain/user/repository/UserRepositoryTest.java, src/test/java/com/sparta/nanglangeats/domain/user/service/UserServiceTest.java
=> [feat] 배송 주소 등록 기능 구현

src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/ReviewController.java, src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/request/ReviewRequest.java, src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/response/ReviewListResponse.java, src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/response/ReviewResponse.java, src/main/java/com/sparta/nanglangeats/domain/review/entity/Review.java, src/main/java/com/sparta/nanglangeats/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/nanglangeats/domain/review/service/ReviewService.java, src/main/java/com/sparta/nanglangeats/global/common/exception/ErrorCode.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> [feat] review 생성, 수정, 삭제 기능 구현

build.gradle, src/main/java/com/sparta/nanglangeats/domain/product/controller/ProductController.java, src/main/java/com/sparta/nanglangeats/domain/product/repository/ProductRepository.java, src/main/java/com/sparta/nanglangeats/domain/product/repository/ProductRepositoryCustom.java, src/main/java/com/sparta/nanglangeats/domain/product/repository/ProductRepositoryCustomImpl.java, src/main/java/com/sparta/nanglangeats/domain/product/service/ProductService.java, src/main/java/com/sparta/nanglangeats/domain/store/controller/StoreController.java, src/main/java/com/sparta/nanglangeats/domain/store/controller/dto/response/StoreListResponse.java, src/main/java/com/sparta/nanglangeats/domain/store/repository/StoreRepository.java, src/main/java/com/sparta/nanglangeats/domain/store/repository/StoreRepositoryCustom.java, src/main/java/com/sparta/nanglangeats/domain/store/repository/StoreRepositoryCustomImpl.java, src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java, src/main/java/com/sparta/nanglangeats/global/config/QuerydslConfig.java
> #77 
- 가게 검색 기능 구현
- 상품 검색 기능 구현
=> [feat] 가게/상품 검색 기능 구현

build.gradle, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/main/java/com/sparta/nanglangeats/global/config/SwaggerConfig.java
=> [feat] Swagger 환경 설정

src/main/java/com/sparta/nanglangeats/domain/auth/controller/AuthController.java, src/main/java/com/sparta/nanglangeats/domain/auth/entity/RefreshToken.java, src/main/java/com/sparta/nanglangeats/domain/auth/repository/RefreshTokenRepository.java, src/main/java/com/sparta/nanglangeats/domain/auth/service/RefreshTokenService.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java
> #96
- Refresh Token 디렉토리 구조 수정
=> [fix] Refresh Token 디렉토리 구조 수정

src/main/java/com/sparta/nanglangeats/domain/auth/controller/AuthController.java, src/main/java/com/sparta/nanglangeats/domain/auth/entity/RefreshToken.java, src/main/java/com/sparta/nanglangeats/domain/auth/repository/RefreshTokenRepository.java, src/main/java/com/sparta/nanglangeats/domain/auth/service/RefreshTokenService.java, src/main/java/com/sparta/nanglangeats/domain/delivery_address/repository/DeliveryAddressRepository.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/DeliveryAddressController.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/request/DeliveryAddressCreateRequest.java, src/main/java/com/sparta/nanglangeats/domain/user/controller/dto/request/DeliveryAddressUpdateRequest.java, src/main/java/com/sparta/nanglangeats/domain/user/entity/DeliveryAddress.java, src/main/java/com/sparta/nanglangeats/domain/user/repository/DeliveryAddressRepository.java, src/main/java/com/sparta/nanglangeats/domain/user/service/DeliveryAddressService.java, src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java, src/main/java/com/sparta/nanglangeats/global/config/security/handler/CustomAuthenticationSuccessHandler.java
> #98
- DeliveryAddress 디렉토리 구조 및 엔드포인트 수정
- 최근 배송지 여부 컬럼 1개의 레코드만 true 유지하도록 수정
=> [fix] DeliveryAddress 수정

src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/ReviewController.java, src/main/java/com/sparta/nanglangeats/domain/review/entity/Review.java, src/main/java/com/sparta/nanglangeats/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/nanglangeats/domain/review/service/ReviewService.java, src/main/java/com/sparta/nanglangeats/domain/store/entity/Store.java, src/main/java/com/sparta/nanglangeats/domain/store/service/StoreService.java
=> [feat] 리뷰 수정 기능 구현

src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/ReviewController.java, src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/response/ReviewListResponse.java, src/main/java/com/sparta/nanglangeats/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/nanglangeats/domain/review/service/ReviewService.java
=> [feat] 가게별 리뷰 목록 조회 기능

src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/ReviewController.java, src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/response/MyReviewListResponse.java, src/main/java/com/sparta/nanglangeats/domain/review/repository/ReviewRepository.java, src/main/java/com/sparta/nanglangeats/domain/review/service/ReviewService.java
=> [feat] 내 리뷰 조회

src/main/java/com/sparta/nanglangeats/domain/order/repository/OrderRepository.java
> #117 
> OrderRepository 오류 수정
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> [fix] OrderRepository 오류 수정

src/main/java/com/sparta/nanglangeats/domain/review/controller/dto/ReviewController.java
=> [fix] 리뷰 엔드포인트 수정

src/main/java/com/sparta/nanglangeats/global/config/SecurityConfig.java
=> [feat] Swagger UI permitAll 설정

src/main/java/com/sparta/nanglangeats/domain/ai/service/GoogleApi.java, src/main/java/com/sparta/nanglangeats/global/config/security/jwt/JwtTokenProvider.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> [Fix] 환경변수 설정
